# Generated by Django 3.2.16 on 2022-11-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, null=True)),
                ('ano', models.IntegerField(null=True)),
                ('versao', models.CharField(default='Unica', max_length=50, null=True)),
                ('motor', models.CharField(max_length=200, null=True)),
                ('cambio', models.CharField(max_length=100, null=True)),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('entre_eixos', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('peso', models.IntegerField(null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='comparativo.continente')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('pais_origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='comparativo.pais')),
            ],
        ),
        migrations.CreateModel(
            name='CorFundoTela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=100, null=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='comparativo.carro')),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='comparativo.marca'),
        ),
    ]
