# Generated by Django 3.2.16 on 2022-11-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparativo', '0002_alter_carro_versao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='id',
        ),
        migrations.AlterField(
            model_name='continente',
            name='nome',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marca',
            name='pais_origem',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nome',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
