# Generated by Django 3.2.16 on 2022-11-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparativo', '0004_alter_marca_pais_origem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='cars_img')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='comparativo.carro')),
            ],
        ),
    ]
