# Generated by Django 3.2.16 on 2022-11-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparativo', '0005_imagemcarro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemcarro',
            name='carro',
        ),
        migrations.AddField(
            model_name='carro',
            name='cor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carro',
            name='path',
            field=models.FileField(null=True, upload_to='cars_img'),
        ),
        migrations.DeleteModel(
            name='CorFundoTela',
        ),
        migrations.DeleteModel(
            name='ImagemCarro',
        ),
    ]
