# Generated by Django 3.2.16 on 2022-11-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparativo', '0006_auto_20221106_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='cor',
            new_name='cor_fundo',
        ),
        migrations.AddField(
            model_name='carro',
            name='cor_botao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
