# Generated by Django 3.2.16 on 2022-11-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparativo', '0007_auto_20221106_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='cor_specs',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
