# Generated by Django 3.2.16 on 2022-11-06 14:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparativo', '0008_carro_cor_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='cor_botao',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='carro',
            name='cor_fundo',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='carro',
            name='cor_specs',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
