# Generated by Django 3.2.16 on 2023-01-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparativo', '0009_auto_20221106_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='nm_descritivo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
