# Generated by Django 3.2.16 on 2023-02-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparativo', '0010_carro_nm_descritivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrosPendentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, null=True)),
                ('ano', models.IntegerField(null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='comparativo.marca')),
            ],
        ),
    ]
