# Generated by Django 3.2.16 on 2023-02-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparativo', '0011_carrospendentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrospendentes',
            name='is_reprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carrospendentes',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
