# Generated by Django 3.2.16 on 2023-02-25 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comparativo', '0012_auto_20230225_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrospendentes',
            name='usr_aprovador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
